[listener]
# Time in seconds allowed for a knock sequence to be completed
# Value must be in the range 1-30.
knock_expiration = 10

pidfile = "/var/run/knock.pid"
client_cfg = "/etc/knockknock/conf.d"

# If knock crashes, open ports (best effort only)
failopen = true
# Ports to open if knock exits unexpectedly
failopen_ports = ["22/tcp"]
# Minimum time to keep ports open after unexpected exit
failopen_min_time = 60


[ufw]
ufw_cmd = "/usr/sbin/ufw"
use_sudo = true


[tcpdump]
log_file = "/tmp/knock-tcpdump.out"
cmd = "/usr/bin/tcpdump"
# Number of lines to allow before truncating log file
truncate_size = 5


[logging]
# debug, info, warning, error, critical
log_level = "info"
# log to syslog. If false, will log to stderr
syslog = false


#[clients]
# Path to client files. One client per file.
# TOML is required format.
# location = "/etc/knock/client.d"
#location = "/tmp/client.d"

##################################################
# Sample configuration for client file
#

# Client name. Used in firewall comment to identify which client
# triggered the rule. If name is blank, filename is used.
# name =

## TOTP initialization secret
#secret = "UBHRQ7SRIQYV7N2JVW6PMRBGHDKSX2O3"

# PIN can be any string you choose, including empty string if
# you do not wish to use a PIN. The PIN should be kept secret
# and is used to salt the time-based one-time password.
#pin = "1234"

## List of ports/protos to open for this client
## Proto is optional
#ports = [ "22/tcp" ]

# Required number of knocks. Max value is 8.
#knock_count = 4

# Number of seconds to leave ports open
#open_duration = 10

